-- SETUP DB TABLES

CREATE TABLE IF NOT EXISTS TASK (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  DUE_DATE DATETIME,
  COMPLETED BOOLEAN DEFAULT FALSE,
  TIME_SPENT DECIMAL DEFAULT 0,
  ESTIMATED_TIME DECIMAL,
  USER_ID INTEGER,
  PRIORITY_ID INTEGER,
  PROJECT_ID INTEGER,
  CREATED_BY VARCHAR(50) NOT NULL,
  CREATED_DATETIME DATETIME NOT NULL DEFAULT SYSDATE,
  UPDATED_BY VARCHAR(50),
  UPDATED_DATETIME DATETIME
);

CREATE TABLE IF NOT EXISTS SUBTASK (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TASK_ID INTEGER NOT NULL,
  PARENT_TASK_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PRIORITY (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  PRIORITY_LEVEL TINYINT NOT NULL,
  CREATED_BY VARCHAR(50) NOT NULL,
  CREATED_DATETIME DATETIME NOT NULL DEFAULT SYSDATE,
  UPDATED_BY VARCHAR(50),
  UPDATED_DATETIME DATETIME
);

CREATE TABLE IF NOT EXISTS REMINDER (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TASK_ID INTEGER NOT NULL,
  REMINDER_TIME DATETIME NOT NULL,
  REMINDER_TYPE VARCHAR(10) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  SENT_TIME DATETIME
);

CREATE TABLE IF NOT EXISTS PROJECT (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  DUE_DATE DATETIME,
  COMPLETED BOOLEAN DEFAULT FALSE,
  CREATED_BY VARCHAR(50) NOT NULL,
  CREATED_DATETIME DATETIME NOT NULL DEFAULT SYSDATE,
  UPDATED_BY VARCHAR(50),
  UPDATED_DATETIME DATETIME
);    

CREATE TABLE IF NOT EXISTS CATEGORY (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  COLOR VARCHAR(7) NOT NULL DEFAULT '#00FF00'
);

CREATE TABLE IF NOT EXISTS PROJECT_CATEGORY (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  CATEGORY_ID INTEGER NOT NULL,
  PROJECT_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS TASK_CATEGORY (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  CATEGORY_ID INTEGER NOT NULL,
  TASK_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS USER (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  USERNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CREATED_BY VARCHAR(50) NOT NULL,
  CREATED_DATETIME DATETIME NOT NULL DEFAULT SYSDATE,
  UPDATED_BY VARCHAR(50),
  UPDATED_DATETIME DATETIME
);

CREATE TABLE IF NOT EXISTS SESSION_TOKEN (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER NOT NULL,
  EXPIRATION DATETIME
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKEN (
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER NOT NULL,
  EXPIRATION DATETIME,
  REVOKED BOOLEAN DEFAULTS FALSE
);
